config/routes.rb
Rails.application.routes.draw do
  
    resources :answers
    post "answers/destroy"
  resources :questions do

  end

  devise_for :admins
  devise_for :users
  resources :details

  resources :learns

  get 'results/survey'

  get 'results/test'

  get 'results/individual'

  resources :tests

  get 'site/index'

  get 'site/about'

  get 'site/learn'

   root 'site#index'
   

end

app/models/learn.rb
class Learn < ActiveRecord::Base
end

app/controllers/learns_controller.rb
class LearnsController < ApplicationController
  before_action :set_learn, only: [:show, :edit, :update, :destroy]

  # GET /learns
  # GET /learns.json
  def index
    @learns = Learn.all
  end

  # GET /learns/1
  # GET /learns/1.json
  def show
  end

  # GET /learns/new
  def new
    @learn = Learn.new
  end

  # GET /learns/1/edit
  def edit
  end

  # POST /learns
  # POST /learns.json
  def create
    @learn = Learn.new(learn_params)

    respond_to do |format|
      if @learn.save
        format.html { redirect_to @learn, notice: 'Learn was successfully created.' }
        format.json { render :show, status: :created, location: @learn }
      else
        format.html { render :new }
        format.json { render json: @learn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /learns/1
  # PATCH/PUT /learns/1.json
  def update
    respond_to do |format|
      if @learn.update(learn_params)
        format.html { redirect_to @learn, notice: 'Learn was successfully updated.' }
        format.json { render :show, status: :ok, location: @learn }
      else
        format.html { render :edit }
        format.json { render json: @learn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /learns/1
  # DELETE /learns/1.json
  def destroy
    @learn.destroy
    respond_to do |format|
      format.html { redirect_to learns_url, notice: 'Learn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_learn
      @learn = Learn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def learn_params
      params.require(:learn).permit(:title, :image, :site, :description, :free)
    end
end

app/helpers/learns_helper.rb
module LearnsHelper
end

app/views/learns/_form.html.erb
<%= form_for(@learn) do |f| %>
  <% if @learn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@learn.errors.count, "error") %> prohibited this learn from being saved:</h2>

      <ul>
      <% @learn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :site %><br>
    <%= f.text_field :site %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :free %><br>
    <%= f.check_box :free %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/learns/edit.html.erb
<h1>Editing learn</h1>

<%= render 'form' %>

<%= link_to 'Show', @learn %> |
<%= link_to 'Back', learns_path %>

app/views/learns/index.html.erb
<article>
	<h1>Where you can learn to code</h1>
<p>Below are a number of online sites that have coding tests and would help you better learn to code.</p>

<section>
	<% @learns.each do |learn| %>
	<section class="learnable">
	<h2><%= learn.title.titleize %></h2>
	<%= learn.image %>
	<p><%= learn.description %>
		<br />
		<span>Link: &nbsp;</span> <%= link_to learn.site, "http://#{learn.site}", :target => "_blank"%>
	</p>
	
	<div>
	<h3>Is this Free?</h3>
	<p><%= learn.free.humanize %></p>
	</div>
	<div>
		<%= link_to 'Show', learn %> | <%= link_to 'Edit', edit_learn_path(learn) %> | <%= link_to 'Destroy', learn, method: :delete, data: { confirm: 'Are you sure?' } %>
	</div>
	</section>
	<% end %>
</section>
<br/>
</article>
<aside>
<%= link_to 'Add a new learning resource', new_learn_path, :class => 'button' %>

</aside>
	

app/views/learns/new.html.erb
<h1>New learn</h1>

<%= render 'form' %>

<%= link_to 'Back', learns_path %>

app/views/learns/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @learn.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= @learn.image %>
</p>

<p>
  <strong>Site:</strong>
  <%= @learn.site %>
</p>

<p>
  <strong>Description:</strong>
  <%= @learn.description %>
</p>

<p>
  <strong>Free:</strong>
  <%= @learn.free %>
</p>

<%= link_to 'Edit', edit_learn_path(@learn) %> |
<%= link_to 'Back', learns_path %>