config/routes.rb
Rails.application.routes.draw do
  
    resources :answers
    post "answers/destroy"
  resources :questions do

  end

  devise_for :admins
  devise_for :users
  resources :details

  resources :learns

  get 'results/survey'

  get 'results/test'

  get 'results/individual'

  resources :tests

  get 'site/index'

  get 'site/about'

  get 'site/learn'

   root 'site#index'
   

end

app/models/detail.rb
class Detail < ActiveRecord::Base
  
  
  validates_uniqueness_of :email
  
  PROFESSIONS = [ "Art Teacher", "Other Teacher", "IT Professional", "Student", "Other"]
  
  TEACHLENGTH = [ "n/a", "0-5 years (NQT)", "5-10 years", "10-15 years", "15-20 years", "20-25 years", "25 years +"]
  
  LOCATION = ["Dublin", "Leinster", "Munster", "Connaught", "Ulster", "Northern Ireland", "UK", "Australia", "USA", "Canada", "Other"]
  
  PROFICIENCY =[ "select", "1 - Basic Understanding", "2 - General Understanding", "3 - Ablility to use program like Photoshop", "4 - Some Understanding of Code", "5 - Advanced Understanding"]
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: [:show, :edit, :update, :destroy]

  # GET /details
  # GET /details.json
  def index
    @details = Detail.all
  end

  # GET /details/1
  # GET /details/1.json
  def show
  end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit
  end

  # POST /details
  # POST /details.json
  def create
    @detail = Detail.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: 'Detail was successfully created.' }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1
  # PATCH/PUT /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to @detail, notice: 'Detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail.destroy
    respond_to do |format|
      format.html { redirect_to details_url, notice: 'Detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_params
      params.require(:detail).permit(:name, :age, :email, :lenghtteach, :profession, :ictlevel, :research)
    end
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_form.html.erb
<%= simple_form_for(@detail) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :label => 'Please tell me your name' %>
    &nbsp;  &nbsp;<%= f.input :age, collection: 10..80, :label => 'How old are you?' %>
    <%= f.input :email, :label => 'Please submit email, so we can send you results' %>

   <%= f.label :profession, 'What Profession/background are you from?'%>
    &nbsp;<%= f.select :profession, Detail::PROFESSIONS, :label => 'What Profession/background are you from?', :required => true %><br /><br />
   <%= f.label :lenghtteach, 'If a teacher, how long have you been teaching?'%>
    &nbsp;<%= f.select :lenghtteach, Detail::TEACHLENGTH, :label => 'If a teacher, how long have you been teaching?', :required => true %><br /><br />
   <%= f.label :location, 'What area do you live/work in?' %>
    &nbsp;<%= f.select :lenghtteach, Detail::LOCATION, :label => 'What area do you live/work in?', :required => true %>
    <br /><br />
   <%= f.label :ictlevel, 'From a scale of one to five, 1 being no competance, and 5 being very competant, how competant are your ICT skills?' %>
    &nbsp;<%= f.select :ictlevel, Detail::PROFICIENCY, :label => 'What area do you live/work in?', :required => true %>
    
    <p>Please click the box to allow your anonymous results being included in this research study.</p>
    <%= f.check_box :research, :name => 'Do you consent', :checked => 'checked', as: :boolean %>
  </div>

  <div class="form-actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/index.html.erb
<h1>Listing details</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th>Lenghtteach</th>
      <th>Profession</th>
      <th>Ictlevel</th>
      <th>Research</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @details.each do |detail| %>
      <tr>
        <td><%= detail.name %></td>
        <td><%= detail.age %></td>
        <td><%= detail.email %></td>
        <td><%= detail.lenghtteach %></td>
        <td><%= detail.profession %></td>
        <td><%= detail.ictlevel %></td>
        <td><%= detail.research %></td>
        <td><%= link_to 'Show', detail %></td>
        <td><%= link_to 'Edit', edit_detail_path(detail) %></td>
        <td><%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detail', new_detail_path %>

app/views/details/new.html.erb
<h1>Please Submit Details before taking the Test</h1>

<%= render 'form' %>
<% if user_signed_in? %>
<%= link_to 'Back', details_path %>
<% else %>
<p></p>
<% end %>

app/views/details/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @detail.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @detail.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @detail.email %>
</p>

<p>
  <strong>Lenghtteach:</strong>
  <%= @detail.lenghtteach %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @detail.profession %>
</p>

<p>
  <strong>Ictlevel:</strong>
  <%= @detail.ictlevel %>
</p>

<p>
  <strong>Research:</strong>
  <%= @detail.research %>
</p>

<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>